install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.76.3/hugo_0.76.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

before_script:
  - git config --global user.name "xudai3"
  - git config --global user.email "xudai3@qq.com"

script:
  - hugo -D

after_success:
  - git clone https://${GITHUB_TOKEN}@github.com/xudai3/xudai3.github.io.git container
  - rm -rf container/*
  - cp -r public/* container
  - cd container
  - git add .
  - git commit -m "Travis update blog"
  - git push -u origin master -f