install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.76.3/hugo_0.76.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

before_script:
  - git config -global user.name "xudai"
  - git config -global user.name "xudai3@qq.com"

script:
  - hugo -D

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - cd public
  - git init
  - git add .
  - git remote add origin https://${GITHUB_TOKEN}@github.com/xudai3/xudai3.github.io.git
  - git commit -m ${MESSAGE}
  - git push -u origin master -f